/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard.index'
import { Route as WidgetDemoAgentIdImport } from './routes/widget-demo.$agentId'
import { Route as EmbedAgentIdImport } from './routes/embed.$agentId'
import { Route as DashboardUsageImport } from './routes/dashboard.usage'
import { Route as DashboardSettingsImport } from './routes/dashboard.settings'
import { Route as DashboardBillingImport } from './routes/dashboard.billing'
import { Route as DashboardAgentsImport } from './routes/dashboard.agents'
import { Route as ChatAgentIdImport } from './routes/chat.$agentId'
import { Route as ApiChatImport } from './routes/api.chat'
import { Route as DashboardSettingsIndexImport } from './routes/dashboard.settings.index'
import { Route as DashboardBillingIndexImport } from './routes/dashboard.billing.index'
import { Route as DashboardAgentsIndexImport } from './routes/dashboard.agents.index'
import { Route as DashboardSettingsPlansImport } from './routes/dashboard.settings.plans'
import { Route as DashboardSettingsMembersImport } from './routes/dashboard.settings.members'
import { Route as DashboardSettingsBillingImport } from './routes/dashboard.settings.billing'
import { Route as DashboardBillingPlansImport } from './routes/dashboard.billing.plans'
import { Route as DashboardAgentsNewImport } from './routes/dashboard.agents.new'
import { Route as DashboardAgentsAgentIdImport } from './routes/dashboard.agents.$agentId'
import { Route as DashboardAgentsAgentIdIndexImport } from './routes/dashboard.agents.$agentId.index'
import { Route as DashboardAgentsAgentIdWidgetImport } from './routes/dashboard.agents.$agentId.widget'
import { Route as DashboardAgentsAgentIdSettingsImport } from './routes/dashboard.agents.$agentId.settings'
import { Route as DashboardAgentsAgentIdKnowledgeImport } from './routes/dashboard.agents.$agentId.knowledge'
import { Route as DashboardAgentsAgentIdDeployImport } from './routes/dashboard.agents.$agentId.deploy'
import { Route as DashboardAgentsAgentIdConversationsImport } from './routes/dashboard.agents.$agentId.conversations'
import { Route as DashboardAgentsAgentIdChatImport } from './routes/dashboard.agents.$agentId.chat'
import { Route as DashboardAgentsAgentIdSettingsIndexImport } from './routes/dashboard.agents.$agentId.settings.index'
import { Route as DashboardAgentsAgentIdKnowledgeIndexImport } from './routes/dashboard.agents.$agentId.knowledge.index'
import { Route as DashboardAgentsAgentIdSettingsSecurityImport } from './routes/dashboard.agents.$agentId.settings.security'
import { Route as DashboardAgentsAgentIdSettingsChatInterfaceImport } from './routes/dashboard.agents.$agentId.settings.chat-interface'
import { Route as DashboardAgentsAgentIdSettingsAiImport } from './routes/dashboard.agents.$agentId.settings.ai'
import { Route as DashboardAgentsAgentIdKnowledgeUrlImport } from './routes/dashboard.agents.$agentId.knowledge.url'
import { Route as DashboardAgentsAgentIdKnowledgeUploadImport } from './routes/dashboard.agents.$agentId.knowledge.upload'
import { Route as DashboardAgentsAgentIdKnowledgeTextImport } from './routes/dashboard.agents.$agentId.knowledge.text'
import { Route as DashboardAgentsAgentIdKnowledgeQnaImport } from './routes/dashboard.agents.$agentId.knowledge.qna'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const WidgetDemoAgentIdRoute = WidgetDemoAgentIdImport.update({
  id: '/widget-demo/$agentId',
  path: '/widget-demo/$agentId',
  getParentRoute: () => rootRoute,
} as any)

const EmbedAgentIdRoute = EmbedAgentIdImport.update({
  id: '/embed/$agentId',
  path: '/embed/$agentId',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsageRoute = DashboardUsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBillingRoute = DashboardBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAgentsRoute = DashboardAgentsImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)

const ChatAgentIdRoute = ChatAgentIdImport.update({
  id: '/chat/$agentId',
  path: '/chat/$agentId',
  getParentRoute: () => rootRoute,
} as any)

const ApiChatRoute = ApiChatImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRoute,
} as any)

const DashboardSettingsIndexRoute = DashboardSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)

const DashboardBillingIndexRoute = DashboardBillingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBillingRoute,
} as any)

const DashboardAgentsIndexRoute = DashboardAgentsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAgentsRoute,
} as any)

const DashboardSettingsPlansRoute = DashboardSettingsPlansImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardSettingsRoute,
} as any)

const DashboardSettingsMembersRoute = DashboardSettingsMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardSettingsRoute,
} as any)

const DashboardSettingsBillingRoute = DashboardSettingsBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardSettingsRoute,
} as any)

const DashboardBillingPlansRoute = DashboardBillingPlansImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardBillingRoute,
} as any)

const DashboardAgentsNewRoute = DashboardAgentsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAgentsRoute,
} as any)

const DashboardAgentsAgentIdRoute = DashboardAgentsAgentIdImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => DashboardAgentsRoute,
} as any)

const DashboardAgentsAgentIdIndexRoute =
  DashboardAgentsAgentIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any)

const DashboardAgentsAgentIdWidgetRoute =
  DashboardAgentsAgentIdWidgetImport.update({
    id: '/widget',
    path: '/widget',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any)

const DashboardAgentsAgentIdSettingsRoute =
  DashboardAgentsAgentIdSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any)

const DashboardAgentsAgentIdKnowledgeRoute =
  DashboardAgentsAgentIdKnowledgeImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any)

const DashboardAgentsAgentIdDeployRoute =
  DashboardAgentsAgentIdDeployImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any)

const DashboardAgentsAgentIdConversationsRoute =
  DashboardAgentsAgentIdConversationsImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any)

const DashboardAgentsAgentIdChatRoute = DashboardAgentsAgentIdChatImport.update(
  {
    id: '/chat',
    path: '/chat',
    getParentRoute: () => DashboardAgentsAgentIdRoute,
  } as any,
)

const DashboardAgentsAgentIdSettingsIndexRoute =
  DashboardAgentsAgentIdSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAgentsAgentIdSettingsRoute,
  } as any)

const DashboardAgentsAgentIdKnowledgeIndexRoute =
  DashboardAgentsAgentIdKnowledgeIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAgentsAgentIdKnowledgeRoute,
  } as any)

const DashboardAgentsAgentIdSettingsSecurityRoute =
  DashboardAgentsAgentIdSettingsSecurityImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardAgentsAgentIdSettingsRoute,
  } as any)

const DashboardAgentsAgentIdSettingsChatInterfaceRoute =
  DashboardAgentsAgentIdSettingsChatInterfaceImport.update({
    id: '/chat-interface',
    path: '/chat-interface',
    getParentRoute: () => DashboardAgentsAgentIdSettingsRoute,
  } as any)

const DashboardAgentsAgentIdSettingsAiRoute =
  DashboardAgentsAgentIdSettingsAiImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => DashboardAgentsAgentIdSettingsRoute,
  } as any)

const DashboardAgentsAgentIdKnowledgeUrlRoute =
  DashboardAgentsAgentIdKnowledgeUrlImport.update({
    id: '/url',
    path: '/url',
    getParentRoute: () => DashboardAgentsAgentIdKnowledgeRoute,
  } as any)

const DashboardAgentsAgentIdKnowledgeUploadRoute =
  DashboardAgentsAgentIdKnowledgeUploadImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => DashboardAgentsAgentIdKnowledgeRoute,
  } as any)

const DashboardAgentsAgentIdKnowledgeTextRoute =
  DashboardAgentsAgentIdKnowledgeTextImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => DashboardAgentsAgentIdKnowledgeRoute,
  } as any)

const DashboardAgentsAgentIdKnowledgeQnaRoute =
  DashboardAgentsAgentIdKnowledgeQnaImport.update({
    id: '/qna',
    path: '/qna',
    getParentRoute: () => DashboardAgentsAgentIdKnowledgeRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/$agentId': {
      id: '/chat/$agentId'
      path: '/chat/$agentId'
      fullPath: '/chat/$agentId'
      preLoaderRoute: typeof ChatAgentIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageImport
      parentRoute: typeof DashboardImport
    }
    '/embed/$agentId': {
      id: '/embed/$agentId'
      path: '/embed/$agentId'
      fullPath: '/embed/$agentId'
      preLoaderRoute: typeof EmbedAgentIdImport
      parentRoute: typeof rootRoute
    }
    '/widget-demo/$agentId': {
      id: '/widget-demo/$agentId'
      path: '/widget-demo/$agentId'
      fullPath: '/widget-demo/$agentId'
      preLoaderRoute: typeof WidgetDemoAgentIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/agents/$agentId': {
      id: '/dashboard/agents/$agentId'
      path: '/$agentId'
      fullPath: '/dashboard/agents/$agentId'
      preLoaderRoute: typeof DashboardAgentsAgentIdImport
      parentRoute: typeof DashboardAgentsImport
    }
    '/dashboard/agents/new': {
      id: '/dashboard/agents/new'
      path: '/new'
      fullPath: '/dashboard/agents/new'
      preLoaderRoute: typeof DashboardAgentsNewImport
      parentRoute: typeof DashboardAgentsImport
    }
    '/dashboard/billing/plans': {
      id: '/dashboard/billing/plans'
      path: '/plans'
      fullPath: '/dashboard/billing/plans'
      preLoaderRoute: typeof DashboardBillingPlansImport
      parentRoute: typeof DashboardBillingImport
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingImport
      parentRoute: typeof DashboardSettingsImport
    }
    '/dashboard/settings/members': {
      id: '/dashboard/settings/members'
      path: '/members'
      fullPath: '/dashboard/settings/members'
      preLoaderRoute: typeof DashboardSettingsMembersImport
      parentRoute: typeof DashboardSettingsImport
    }
    '/dashboard/settings/plans': {
      id: '/dashboard/settings/plans'
      path: '/plans'
      fullPath: '/dashboard/settings/plans'
      preLoaderRoute: typeof DashboardSettingsPlansImport
      parentRoute: typeof DashboardSettingsImport
    }
    '/dashboard/agents/': {
      id: '/dashboard/agents/'
      path: '/'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexImport
      parentRoute: typeof DashboardAgentsImport
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexImport
      parentRoute: typeof DashboardBillingImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexImport
      parentRoute: typeof DashboardSettingsImport
    }
    '/dashboard/agents/$agentId/chat': {
      id: '/dashboard/agents/$agentId/chat'
      path: '/chat'
      fullPath: '/dashboard/agents/$agentId/chat'
      preLoaderRoute: typeof DashboardAgentsAgentIdChatImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/conversations': {
      id: '/dashboard/agents/$agentId/conversations'
      path: '/conversations'
      fullPath: '/dashboard/agents/$agentId/conversations'
      preLoaderRoute: typeof DashboardAgentsAgentIdConversationsImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/deploy': {
      id: '/dashboard/agents/$agentId/deploy'
      path: '/deploy'
      fullPath: '/dashboard/agents/$agentId/deploy'
      preLoaderRoute: typeof DashboardAgentsAgentIdDeployImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/knowledge': {
      id: '/dashboard/agents/$agentId/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/agents/$agentId/knowledge'
      preLoaderRoute: typeof DashboardAgentsAgentIdKnowledgeImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/settings': {
      id: '/dashboard/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/dashboard/agents/$agentId/settings'
      preLoaderRoute: typeof DashboardAgentsAgentIdSettingsImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/widget': {
      id: '/dashboard/agents/$agentId/widget'
      path: '/widget'
      fullPath: '/dashboard/agents/$agentId/widget'
      preLoaderRoute: typeof DashboardAgentsAgentIdWidgetImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/': {
      id: '/dashboard/agents/$agentId/'
      path: '/'
      fullPath: '/dashboard/agents/$agentId/'
      preLoaderRoute: typeof DashboardAgentsAgentIdIndexImport
      parentRoute: typeof DashboardAgentsAgentIdImport
    }
    '/dashboard/agents/$agentId/knowledge/qna': {
      id: '/dashboard/agents/$agentId/knowledge/qna'
      path: '/qna'
      fullPath: '/dashboard/agents/$agentId/knowledge/qna'
      preLoaderRoute: typeof DashboardAgentsAgentIdKnowledgeQnaImport
      parentRoute: typeof DashboardAgentsAgentIdKnowledgeImport
    }
    '/dashboard/agents/$agentId/knowledge/text': {
      id: '/dashboard/agents/$agentId/knowledge/text'
      path: '/text'
      fullPath: '/dashboard/agents/$agentId/knowledge/text'
      preLoaderRoute: typeof DashboardAgentsAgentIdKnowledgeTextImport
      parentRoute: typeof DashboardAgentsAgentIdKnowledgeImport
    }
    '/dashboard/agents/$agentId/knowledge/upload': {
      id: '/dashboard/agents/$agentId/knowledge/upload'
      path: '/upload'
      fullPath: '/dashboard/agents/$agentId/knowledge/upload'
      preLoaderRoute: typeof DashboardAgentsAgentIdKnowledgeUploadImport
      parentRoute: typeof DashboardAgentsAgentIdKnowledgeImport
    }
    '/dashboard/agents/$agentId/knowledge/url': {
      id: '/dashboard/agents/$agentId/knowledge/url'
      path: '/url'
      fullPath: '/dashboard/agents/$agentId/knowledge/url'
      preLoaderRoute: typeof DashboardAgentsAgentIdKnowledgeUrlImport
      parentRoute: typeof DashboardAgentsAgentIdKnowledgeImport
    }
    '/dashboard/agents/$agentId/settings/ai': {
      id: '/dashboard/agents/$agentId/settings/ai'
      path: '/ai'
      fullPath: '/dashboard/agents/$agentId/settings/ai'
      preLoaderRoute: typeof DashboardAgentsAgentIdSettingsAiImport
      parentRoute: typeof DashboardAgentsAgentIdSettingsImport
    }
    '/dashboard/agents/$agentId/settings/chat-interface': {
      id: '/dashboard/agents/$agentId/settings/chat-interface'
      path: '/chat-interface'
      fullPath: '/dashboard/agents/$agentId/settings/chat-interface'
      preLoaderRoute: typeof DashboardAgentsAgentIdSettingsChatInterfaceImport
      parentRoute: typeof DashboardAgentsAgentIdSettingsImport
    }
    '/dashboard/agents/$agentId/settings/security': {
      id: '/dashboard/agents/$agentId/settings/security'
      path: '/security'
      fullPath: '/dashboard/agents/$agentId/settings/security'
      preLoaderRoute: typeof DashboardAgentsAgentIdSettingsSecurityImport
      parentRoute: typeof DashboardAgentsAgentIdSettingsImport
    }
    '/dashboard/agents/$agentId/knowledge/': {
      id: '/dashboard/agents/$agentId/knowledge/'
      path: '/'
      fullPath: '/dashboard/agents/$agentId/knowledge/'
      preLoaderRoute: typeof DashboardAgentsAgentIdKnowledgeIndexImport
      parentRoute: typeof DashboardAgentsAgentIdKnowledgeImport
    }
    '/dashboard/agents/$agentId/settings/': {
      id: '/dashboard/agents/$agentId/settings/'
      path: '/'
      fullPath: '/dashboard/agents/$agentId/settings/'
      preLoaderRoute: typeof DashboardAgentsAgentIdSettingsIndexImport
      parentRoute: typeof DashboardAgentsAgentIdSettingsImport
    }
  }
}

// Create and export the route tree

interface DashboardAgentsAgentIdKnowledgeRouteChildren {
  DashboardAgentsAgentIdKnowledgeQnaRoute: typeof DashboardAgentsAgentIdKnowledgeQnaRoute
  DashboardAgentsAgentIdKnowledgeTextRoute: typeof DashboardAgentsAgentIdKnowledgeTextRoute
  DashboardAgentsAgentIdKnowledgeUploadRoute: typeof DashboardAgentsAgentIdKnowledgeUploadRoute
  DashboardAgentsAgentIdKnowledgeUrlRoute: typeof DashboardAgentsAgentIdKnowledgeUrlRoute
  DashboardAgentsAgentIdKnowledgeIndexRoute: typeof DashboardAgentsAgentIdKnowledgeIndexRoute
}

const DashboardAgentsAgentIdKnowledgeRouteChildren: DashboardAgentsAgentIdKnowledgeRouteChildren =
  {
    DashboardAgentsAgentIdKnowledgeQnaRoute:
      DashboardAgentsAgentIdKnowledgeQnaRoute,
    DashboardAgentsAgentIdKnowledgeTextRoute:
      DashboardAgentsAgentIdKnowledgeTextRoute,
    DashboardAgentsAgentIdKnowledgeUploadRoute:
      DashboardAgentsAgentIdKnowledgeUploadRoute,
    DashboardAgentsAgentIdKnowledgeUrlRoute:
      DashboardAgentsAgentIdKnowledgeUrlRoute,
    DashboardAgentsAgentIdKnowledgeIndexRoute:
      DashboardAgentsAgentIdKnowledgeIndexRoute,
  }

const DashboardAgentsAgentIdKnowledgeRouteWithChildren =
  DashboardAgentsAgentIdKnowledgeRoute._addFileChildren(
    DashboardAgentsAgentIdKnowledgeRouteChildren,
  )

interface DashboardAgentsAgentIdSettingsRouteChildren {
  DashboardAgentsAgentIdSettingsAiRoute: typeof DashboardAgentsAgentIdSettingsAiRoute
  DashboardAgentsAgentIdSettingsChatInterfaceRoute: typeof DashboardAgentsAgentIdSettingsChatInterfaceRoute
  DashboardAgentsAgentIdSettingsSecurityRoute: typeof DashboardAgentsAgentIdSettingsSecurityRoute
  DashboardAgentsAgentIdSettingsIndexRoute: typeof DashboardAgentsAgentIdSettingsIndexRoute
}

const DashboardAgentsAgentIdSettingsRouteChildren: DashboardAgentsAgentIdSettingsRouteChildren =
  {
    DashboardAgentsAgentIdSettingsAiRoute:
      DashboardAgentsAgentIdSettingsAiRoute,
    DashboardAgentsAgentIdSettingsChatInterfaceRoute:
      DashboardAgentsAgentIdSettingsChatInterfaceRoute,
    DashboardAgentsAgentIdSettingsSecurityRoute:
      DashboardAgentsAgentIdSettingsSecurityRoute,
    DashboardAgentsAgentIdSettingsIndexRoute:
      DashboardAgentsAgentIdSettingsIndexRoute,
  }

const DashboardAgentsAgentIdSettingsRouteWithChildren =
  DashboardAgentsAgentIdSettingsRoute._addFileChildren(
    DashboardAgentsAgentIdSettingsRouteChildren,
  )

interface DashboardAgentsAgentIdRouteChildren {
  DashboardAgentsAgentIdChatRoute: typeof DashboardAgentsAgentIdChatRoute
  DashboardAgentsAgentIdConversationsRoute: typeof DashboardAgentsAgentIdConversationsRoute
  DashboardAgentsAgentIdDeployRoute: typeof DashboardAgentsAgentIdDeployRoute
  DashboardAgentsAgentIdKnowledgeRoute: typeof DashboardAgentsAgentIdKnowledgeRouteWithChildren
  DashboardAgentsAgentIdSettingsRoute: typeof DashboardAgentsAgentIdSettingsRouteWithChildren
  DashboardAgentsAgentIdWidgetRoute: typeof DashboardAgentsAgentIdWidgetRoute
  DashboardAgentsAgentIdIndexRoute: typeof DashboardAgentsAgentIdIndexRoute
}

const DashboardAgentsAgentIdRouteChildren: DashboardAgentsAgentIdRouteChildren =
  {
    DashboardAgentsAgentIdChatRoute: DashboardAgentsAgentIdChatRoute,
    DashboardAgentsAgentIdConversationsRoute:
      DashboardAgentsAgentIdConversationsRoute,
    DashboardAgentsAgentIdDeployRoute: DashboardAgentsAgentIdDeployRoute,
    DashboardAgentsAgentIdKnowledgeRoute:
      DashboardAgentsAgentIdKnowledgeRouteWithChildren,
    DashboardAgentsAgentIdSettingsRoute:
      DashboardAgentsAgentIdSettingsRouteWithChildren,
    DashboardAgentsAgentIdWidgetRoute: DashboardAgentsAgentIdWidgetRoute,
    DashboardAgentsAgentIdIndexRoute: DashboardAgentsAgentIdIndexRoute,
  }

const DashboardAgentsAgentIdRouteWithChildren =
  DashboardAgentsAgentIdRoute._addFileChildren(
    DashboardAgentsAgentIdRouteChildren,
  )

interface DashboardAgentsRouteChildren {
  DashboardAgentsAgentIdRoute: typeof DashboardAgentsAgentIdRouteWithChildren
  DashboardAgentsNewRoute: typeof DashboardAgentsNewRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardAgentsRouteChildren: DashboardAgentsRouteChildren = {
  DashboardAgentsAgentIdRoute: DashboardAgentsAgentIdRouteWithChildren,
  DashboardAgentsNewRoute: DashboardAgentsNewRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardAgentsRouteWithChildren = DashboardAgentsRoute._addFileChildren(
  DashboardAgentsRouteChildren,
)

interface DashboardBillingRouteChildren {
  DashboardBillingPlansRoute: typeof DashboardBillingPlansRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
}

const DashboardBillingRouteChildren: DashboardBillingRouteChildren = {
  DashboardBillingPlansRoute: DashboardBillingPlansRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
}

const DashboardBillingRouteWithChildren =
  DashboardBillingRoute._addFileChildren(DashboardBillingRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsMembersRoute: typeof DashboardSettingsMembersRoute
  DashboardSettingsPlansRoute: typeof DashboardSettingsPlansRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsMembersRoute: DashboardSettingsMembersRoute,
  DashboardSettingsPlansRoute: DashboardSettingsPlansRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/embed/$agentId': typeof EmbedAgentIdRoute
  '/widget-demo/$agentId': typeof WidgetDemoAgentIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRouteWithChildren
  '/dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/dashboard/billing/plans': typeof DashboardBillingPlansRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/members': typeof DashboardSettingsMembersRoute
  '/dashboard/settings/plans': typeof DashboardSettingsPlansRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/agents/$agentId/chat': typeof DashboardAgentsAgentIdChatRoute
  '/dashboard/agents/$agentId/conversations': typeof DashboardAgentsAgentIdConversationsRoute
  '/dashboard/agents/$agentId/deploy': typeof DashboardAgentsAgentIdDeployRoute
  '/dashboard/agents/$agentId/knowledge': typeof DashboardAgentsAgentIdKnowledgeRouteWithChildren
  '/dashboard/agents/$agentId/settings': typeof DashboardAgentsAgentIdSettingsRouteWithChildren
  '/dashboard/agents/$agentId/widget': typeof DashboardAgentsAgentIdWidgetRoute
  '/dashboard/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/dashboard/agents/$agentId/knowledge/qna': typeof DashboardAgentsAgentIdKnowledgeQnaRoute
  '/dashboard/agents/$agentId/knowledge/text': typeof DashboardAgentsAgentIdKnowledgeTextRoute
  '/dashboard/agents/$agentId/knowledge/upload': typeof DashboardAgentsAgentIdKnowledgeUploadRoute
  '/dashboard/agents/$agentId/knowledge/url': typeof DashboardAgentsAgentIdKnowledgeUrlRoute
  '/dashboard/agents/$agentId/settings/ai': typeof DashboardAgentsAgentIdSettingsAiRoute
  '/dashboard/agents/$agentId/settings/chat-interface': typeof DashboardAgentsAgentIdSettingsChatInterfaceRoute
  '/dashboard/agents/$agentId/settings/security': typeof DashboardAgentsAgentIdSettingsSecurityRoute
  '/dashboard/agents/$agentId/knowledge/': typeof DashboardAgentsAgentIdKnowledgeIndexRoute
  '/dashboard/agents/$agentId/settings/': typeof DashboardAgentsAgentIdSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/embed/$agentId': typeof EmbedAgentIdRoute
  '/widget-demo/$agentId': typeof WidgetDemoAgentIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/dashboard/billing/plans': typeof DashboardBillingPlansRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/members': typeof DashboardSettingsMembersRoute
  '/dashboard/settings/plans': typeof DashboardSettingsPlansRoute
  '/dashboard/agents': typeof DashboardAgentsIndexRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/agents/$agentId/chat': typeof DashboardAgentsAgentIdChatRoute
  '/dashboard/agents/$agentId/conversations': typeof DashboardAgentsAgentIdConversationsRoute
  '/dashboard/agents/$agentId/deploy': typeof DashboardAgentsAgentIdDeployRoute
  '/dashboard/agents/$agentId/widget': typeof DashboardAgentsAgentIdWidgetRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/dashboard/agents/$agentId/knowledge/qna': typeof DashboardAgentsAgentIdKnowledgeQnaRoute
  '/dashboard/agents/$agentId/knowledge/text': typeof DashboardAgentsAgentIdKnowledgeTextRoute
  '/dashboard/agents/$agentId/knowledge/upload': typeof DashboardAgentsAgentIdKnowledgeUploadRoute
  '/dashboard/agents/$agentId/knowledge/url': typeof DashboardAgentsAgentIdKnowledgeUrlRoute
  '/dashboard/agents/$agentId/settings/ai': typeof DashboardAgentsAgentIdSettingsAiRoute
  '/dashboard/agents/$agentId/settings/chat-interface': typeof DashboardAgentsAgentIdSettingsChatInterfaceRoute
  '/dashboard/agents/$agentId/settings/security': typeof DashboardAgentsAgentIdSettingsSecurityRoute
  '/dashboard/agents/$agentId/knowledge': typeof DashboardAgentsAgentIdKnowledgeIndexRoute
  '/dashboard/agents/$agentId/settings': typeof DashboardAgentsAgentIdSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/embed/$agentId': typeof EmbedAgentIdRoute
  '/widget-demo/$agentId': typeof WidgetDemoAgentIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRouteWithChildren
  '/dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/dashboard/billing/plans': typeof DashboardBillingPlansRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/members': typeof DashboardSettingsMembersRoute
  '/dashboard/settings/plans': typeof DashboardSettingsPlansRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/agents/$agentId/chat': typeof DashboardAgentsAgentIdChatRoute
  '/dashboard/agents/$agentId/conversations': typeof DashboardAgentsAgentIdConversationsRoute
  '/dashboard/agents/$agentId/deploy': typeof DashboardAgentsAgentIdDeployRoute
  '/dashboard/agents/$agentId/knowledge': typeof DashboardAgentsAgentIdKnowledgeRouteWithChildren
  '/dashboard/agents/$agentId/settings': typeof DashboardAgentsAgentIdSettingsRouteWithChildren
  '/dashboard/agents/$agentId/widget': typeof DashboardAgentsAgentIdWidgetRoute
  '/dashboard/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/dashboard/agents/$agentId/knowledge/qna': typeof DashboardAgentsAgentIdKnowledgeQnaRoute
  '/dashboard/agents/$agentId/knowledge/text': typeof DashboardAgentsAgentIdKnowledgeTextRoute
  '/dashboard/agents/$agentId/knowledge/upload': typeof DashboardAgentsAgentIdKnowledgeUploadRoute
  '/dashboard/agents/$agentId/knowledge/url': typeof DashboardAgentsAgentIdKnowledgeUrlRoute
  '/dashboard/agents/$agentId/settings/ai': typeof DashboardAgentsAgentIdSettingsAiRoute
  '/dashboard/agents/$agentId/settings/chat-interface': typeof DashboardAgentsAgentIdSettingsChatInterfaceRoute
  '/dashboard/agents/$agentId/settings/security': typeof DashboardAgentsAgentIdSettingsSecurityRoute
  '/dashboard/agents/$agentId/knowledge/': typeof DashboardAgentsAgentIdKnowledgeIndexRoute
  '/dashboard/agents/$agentId/settings/': typeof DashboardAgentsAgentIdSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/chat'
    | '/chat/$agentId'
    | '/dashboard/agents'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/embed/$agentId'
    | '/widget-demo/$agentId'
    | '/dashboard/'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/billing/plans'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/agents/'
    | '/dashboard/billing/'
    | '/dashboard/settings/'
    | '/dashboard/agents/$agentId/chat'
    | '/dashboard/agents/$agentId/conversations'
    | '/dashboard/agents/$agentId/deploy'
    | '/dashboard/agents/$agentId/knowledge'
    | '/dashboard/agents/$agentId/settings'
    | '/dashboard/agents/$agentId/widget'
    | '/dashboard/agents/$agentId/'
    | '/dashboard/agents/$agentId/knowledge/qna'
    | '/dashboard/agents/$agentId/knowledge/text'
    | '/dashboard/agents/$agentId/knowledge/upload'
    | '/dashboard/agents/$agentId/knowledge/url'
    | '/dashboard/agents/$agentId/settings/ai'
    | '/dashboard/agents/$agentId/settings/chat-interface'
    | '/dashboard/agents/$agentId/settings/security'
    | '/dashboard/agents/$agentId/knowledge/'
    | '/dashboard/agents/$agentId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/chat/$agentId'
    | '/dashboard/usage'
    | '/embed/$agentId'
    | '/widget-demo/$agentId'
    | '/dashboard'
    | '/dashboard/agents/new'
    | '/dashboard/billing/plans'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/agents'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/dashboard/agents/$agentId/chat'
    | '/dashboard/agents/$agentId/conversations'
    | '/dashboard/agents/$agentId/deploy'
    | '/dashboard/agents/$agentId/widget'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/$agentId/knowledge/qna'
    | '/dashboard/agents/$agentId/knowledge/text'
    | '/dashboard/agents/$agentId/knowledge/upload'
    | '/dashboard/agents/$agentId/knowledge/url'
    | '/dashboard/agents/$agentId/settings/ai'
    | '/dashboard/agents/$agentId/settings/chat-interface'
    | '/dashboard/agents/$agentId/settings/security'
    | '/dashboard/agents/$agentId/knowledge'
    | '/dashboard/agents/$agentId/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/chat'
    | '/chat/$agentId'
    | '/dashboard/agents'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/embed/$agentId'
    | '/widget-demo/$agentId'
    | '/dashboard/'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/billing/plans'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/agents/'
    | '/dashboard/billing/'
    | '/dashboard/settings/'
    | '/dashboard/agents/$agentId/chat'
    | '/dashboard/agents/$agentId/conversations'
    | '/dashboard/agents/$agentId/deploy'
    | '/dashboard/agents/$agentId/knowledge'
    | '/dashboard/agents/$agentId/settings'
    | '/dashboard/agents/$agentId/widget'
    | '/dashboard/agents/$agentId/'
    | '/dashboard/agents/$agentId/knowledge/qna'
    | '/dashboard/agents/$agentId/knowledge/text'
    | '/dashboard/agents/$agentId/knowledge/upload'
    | '/dashboard/agents/$agentId/knowledge/url'
    | '/dashboard/agents/$agentId/settings/ai'
    | '/dashboard/agents/$agentId/settings/chat-interface'
    | '/dashboard/agents/$agentId/settings/security'
    | '/dashboard/agents/$agentId/knowledge/'
    | '/dashboard/agents/$agentId/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ChatAgentIdRoute: typeof ChatAgentIdRoute
  EmbedAgentIdRoute: typeof EmbedAgentIdRoute
  WidgetDemoAgentIdRoute: typeof WidgetDemoAgentIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ChatAgentIdRoute: ChatAgentIdRoute,
  EmbedAgentIdRoute: EmbedAgentIdRoute,
  WidgetDemoAgentIdRoute: WidgetDemoAgentIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/api/chat",
        "/chat/$agentId",
        "/embed/$agentId",
        "/widget-demo/$agentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/agents",
        "/dashboard/billing",
        "/dashboard/settings",
        "/dashboard/usage",
        "/dashboard/"
      ]
    },
    "/api/chat": {
      "filePath": "api.chat.tsx"
    },
    "/chat/$agentId": {
      "filePath": "chat.$agentId.tsx"
    },
    "/dashboard/agents": {
      "filePath": "dashboard.agents.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/agents/$agentId",
        "/dashboard/agents/new",
        "/dashboard/agents/"
      ]
    },
    "/dashboard/billing": {
      "filePath": "dashboard.billing.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/billing/plans",
        "/dashboard/billing/"
      ]
    },
    "/dashboard/settings": {
      "filePath": "dashboard.settings.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/settings/billing",
        "/dashboard/settings/members",
        "/dashboard/settings/plans",
        "/dashboard/settings/"
      ]
    },
    "/dashboard/usage": {
      "filePath": "dashboard.usage.tsx",
      "parent": "/dashboard"
    },
    "/embed/$agentId": {
      "filePath": "embed.$agentId.tsx"
    },
    "/widget-demo/$agentId": {
      "filePath": "widget-demo.$agentId.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard.index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/agents/$agentId": {
      "filePath": "dashboard.agents.$agentId.tsx",
      "parent": "/dashboard/agents",
      "children": [
        "/dashboard/agents/$agentId/chat",
        "/dashboard/agents/$agentId/conversations",
        "/dashboard/agents/$agentId/deploy",
        "/dashboard/agents/$agentId/knowledge",
        "/dashboard/agents/$agentId/settings",
        "/dashboard/agents/$agentId/widget",
        "/dashboard/agents/$agentId/"
      ]
    },
    "/dashboard/agents/new": {
      "filePath": "dashboard.agents.new.tsx",
      "parent": "/dashboard/agents"
    },
    "/dashboard/billing/plans": {
      "filePath": "dashboard.billing.plans.tsx",
      "parent": "/dashboard/billing"
    },
    "/dashboard/settings/billing": {
      "filePath": "dashboard.settings.billing.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/settings/members": {
      "filePath": "dashboard.settings.members.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/settings/plans": {
      "filePath": "dashboard.settings.plans.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/agents/": {
      "filePath": "dashboard.agents.index.tsx",
      "parent": "/dashboard/agents"
    },
    "/dashboard/billing/": {
      "filePath": "dashboard.billing.index.tsx",
      "parent": "/dashboard/billing"
    },
    "/dashboard/settings/": {
      "filePath": "dashboard.settings.index.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/agents/$agentId/chat": {
      "filePath": "dashboard.agents.$agentId.chat.tsx",
      "parent": "/dashboard/agents/$agentId"
    },
    "/dashboard/agents/$agentId/conversations": {
      "filePath": "dashboard.agents.$agentId.conversations.tsx",
      "parent": "/dashboard/agents/$agentId"
    },
    "/dashboard/agents/$agentId/deploy": {
      "filePath": "dashboard.agents.$agentId.deploy.tsx",
      "parent": "/dashboard/agents/$agentId"
    },
    "/dashboard/agents/$agentId/knowledge": {
      "filePath": "dashboard.agents.$agentId.knowledge.tsx",
      "parent": "/dashboard/agents/$agentId",
      "children": [
        "/dashboard/agents/$agentId/knowledge/qna",
        "/dashboard/agents/$agentId/knowledge/text",
        "/dashboard/agents/$agentId/knowledge/upload",
        "/dashboard/agents/$agentId/knowledge/url",
        "/dashboard/agents/$agentId/knowledge/"
      ]
    },
    "/dashboard/agents/$agentId/settings": {
      "filePath": "dashboard.agents.$agentId.settings.tsx",
      "parent": "/dashboard/agents/$agentId",
      "children": [
        "/dashboard/agents/$agentId/settings/ai",
        "/dashboard/agents/$agentId/settings/chat-interface",
        "/dashboard/agents/$agentId/settings/security",
        "/dashboard/agents/$agentId/settings/"
      ]
    },
    "/dashboard/agents/$agentId/widget": {
      "filePath": "dashboard.agents.$agentId.widget.tsx",
      "parent": "/dashboard/agents/$agentId"
    },
    "/dashboard/agents/$agentId/": {
      "filePath": "dashboard.agents.$agentId.index.tsx",
      "parent": "/dashboard/agents/$agentId"
    },
    "/dashboard/agents/$agentId/knowledge/qna": {
      "filePath": "dashboard.agents.$agentId.knowledge.qna.tsx",
      "parent": "/dashboard/agents/$agentId/knowledge"
    },
    "/dashboard/agents/$agentId/knowledge/text": {
      "filePath": "dashboard.agents.$agentId.knowledge.text.tsx",
      "parent": "/dashboard/agents/$agentId/knowledge"
    },
    "/dashboard/agents/$agentId/knowledge/upload": {
      "filePath": "dashboard.agents.$agentId.knowledge.upload.tsx",
      "parent": "/dashboard/agents/$agentId/knowledge"
    },
    "/dashboard/agents/$agentId/knowledge/url": {
      "filePath": "dashboard.agents.$agentId.knowledge.url.tsx",
      "parent": "/dashboard/agents/$agentId/knowledge"
    },
    "/dashboard/agents/$agentId/settings/ai": {
      "filePath": "dashboard.agents.$agentId.settings.ai.tsx",
      "parent": "/dashboard/agents/$agentId/settings"
    },
    "/dashboard/agents/$agentId/settings/chat-interface": {
      "filePath": "dashboard.agents.$agentId.settings.chat-interface.tsx",
      "parent": "/dashboard/agents/$agentId/settings"
    },
    "/dashboard/agents/$agentId/settings/security": {
      "filePath": "dashboard.agents.$agentId.settings.security.tsx",
      "parent": "/dashboard/agents/$agentId/settings"
    },
    "/dashboard/agents/$agentId/knowledge/": {
      "filePath": "dashboard.agents.$agentId.knowledge.index.tsx",
      "parent": "/dashboard/agents/$agentId/knowledge"
    },
    "/dashboard/agents/$agentId/settings/": {
      "filePath": "dashboard.agents.$agentId.settings.index.tsx",
      "parent": "/dashboard/agents/$agentId/settings"
    }
  }
}
ROUTE_MANIFEST_END */
